version: "2.2"
services:
  mmcls:
    shm_size: '2gb'
    runtime: nvidia
    build: 
      context: .
      args:
        IMAGE: supervisely/base-pytorch:6.0.21
    ports:
      - "8888:22"
    volumes:
      - "./data:/data"
